#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Decide how important it is for the user to see this message
PRIORITY=high

db_input $PRIORITY moodle-site-feature-kaltura/db_host || true
db_input $PRIORITY moodle-site-feature-kaltura/db_port || true
db_input $PRIORITY moodle-site-feature-kaltura/db_database || true
db_input $PRIORITY moodle-site-feature-kaltura/db_user || true
db_input $PRIORITY moodle-site-feature-kaltura/db_pass || true
db_go
db_input $PRIORITY moodle-site-feature-kaltura/salt || true
db_go

db_input $PRIORITY moodle-site-feature-kaltura/servername || true
db_input $PRIORITY moodle-site-feature-kaltura/serveralias || true
db_input $PRIORITY moodle-site-feature-kaltura/serverredirects || true
db_go
db_input $PRIORITY moodle-site-feature-kaltura/enabledav || true
db_input $PRIORITY moodle-site-feature-kaltura/usessl || true
db_go
db_get moodle-site-feature-kaltura/usessl
if [ "${RET}" = "true" ]; then
    db_set moodle-site-feature-kaltura/serverport 443 || true
    db_input $PRIORITY moodle-site-feature-kaltura/serverip || true
    db_go
else
    db_set moodle-site-feature-kaltura/serverport 80 || true
    db_set moodle-site-feature-kaltura/serverip '*' || true
fi
